apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastfood-payment-api
  labels:
    app: fastfood-payment-api
spec:
  template:
    metadata:
      name: fastfood-payment-api
      labels:
        app: fastfood-payment-api
    spec:
      containers:
        - name: fastfood-payment-api
          image: 339713094046.dkr.ecr.us-east-1.amazonaws.com/ecr-fastfood_payment
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /health/live
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 0.5
              memory: 400Mi
            requests:
              cpu: 0.2
              memory: 128Mi 
          env:
          - name: ConnectionStrings__MongoConnection
            valueFrom:
              secretKeyRef:
                name: fastfood-payment-secret
                key: ConnectionStrings__MongoConnection
          - name: ConnectionStrings__MongoDatabase
            valueFrom:
              secretKeyRef:
                name: fastfood-payment-secret
                key: ConnectionStrings__MongoDatabase
          - name: ConnectionStrings__PaymentCollection
            valueFrom:
              secretKeyRef:
                name: fastfood-payment-secret
                key: ConnectionStrings__PaymentCollection
          - name: MercadoPago__AccessToken
            valueFrom:
              secretKeyRef:
                name: fastfood-payment-secret
                key: MercadoPago__AccessToken
          - name: MercadoPago__BaseUrl
            valueFrom:
              secretKeyRef:
                name: fastfood-payment-secret
                key: MercadoPago__BaseUrl
          - name: MercadoPago__UserId
            valueFrom:
              secretKeyRef:
                name: fastfood-payment-secret
                key: MercadoPago__UserId
          - name: MercadoPago__ExternalPosId
            valueFrom:
              secretKeyRef:
                name: fastfood-payment-secret
                key: MercadoPago__ExternalPosId
          - name: RabbitMQ__HostName
            valueFrom:
              secretKeyRef:
                name: fastfood-orders-secret
                key: RabbitMQ__HostName
          - name: RabbitMQ__UserName
            valueFrom:
              secretKeyRef:
                name: fastfood-orders-secret
                key: RabbitMQ__UserName
          - name: RabbitMQ__Password
            valueFrom:
              secretKeyRef:
                name: fastfood-orders-secret
                key: RabbitMQ__Password
          - name: RabbitMQ__PaymentQueueName
            valueFrom:
              secretKeyRef:
                name: fastfood-orders-secret
                key: RabbitMQ__PaymentQueueName
          - name: RabbitMQ__ProductionQueueName
            valueFrom:
              secretKeyRef:
                name: fastfood-orders-secret
                key: RabbitMQ__ProductionQueueName
          - name: RabbitMQ__OrderQueueName
            valueFrom:
              secretKeyRef:
                name: fastfood-orders-secret
                key: RabbitMQ__OrderQueueName
          - name: Email__Username
            valueFrom:
              secretKeyRef:
                name: fastfood-orders-secret
                key: Email__Username
          - name: Email__Password
            valueFrom:
              secretKeyRef:
                name: fastfood-orders-secret
                key: Email__Password
  replicas: 1
  selector:
    matchLabels:
      app: fastfood-payment-api