apiVersion: v1
kind: Service
metadata:
  name: fastfood-payment
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: fastfood-lb
spec:
  type: LoadBalancer
  selector:
    app: fastfood-payment-api
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
